### ISSUE TITLE
Referer and caching

### ISSUE THREAD

**Issue by swick** [alexfernandez/librecounter#23]
In firefox (linux, new profile), the link and the tracking image both get a referer of `librecounter.org`. On chrome the referer seems to get passed along but the image gets cached and subsequent views won't get recorded.

**Comment by alexfernandez** [comment]
Hi, sorry for the delay. Help me understand both issues. I just accessed [https://pinchito.es/](https://pinchito.es/) using Firefox and got back in the server the correct referer:

```
[IP] - - [20/Jul/2024:18:42:55 +0000] "GET /counter.svg HTTP/1.1" 200 1471 "https://pinchito.es/" "Mozilla/5.0 [...] Firefox/115.0"
```

On Chrome got the same, refreshed the page and got several hits so I don't see the image get cached. Thanks!

**Comment by swick** [comment]
Looks like I didn't actually use a new profile and the behavior is caused by the umatrix extension. No idea what went wrong in chrome though. I only checked the client side and maybe I read the debugger wrong.

**Comment by swick** [comment]
Actually, maybe it makes sense to change the snippet users include to use the "real" URL (e.g. https://librecounter.org/pinchito.es/show) instead of the one that redirects to the referrer (https://librecounter.org/referer/show) in case the referrer is wrong?

**Comment by alexfernandez** [comment]
Sorry for the long delay, I prefer to have the referrer by default because it works for the majority of people.
